### ISSUE TITLE
The notebook CategoryOfRepresentations.ipynb is different from the one I used in my Bachelor talk

### ISSUE THREAD

**Issue by Tschitschibor** [homalg-project/CatReps#18]
Should I commit the new version that is now in my (private) repo [bachelorarbeit/catreps-seminar/CategoryOfRepresentations.ipynb](https://github.com/Tschitschibor/bachelorarbeit/blob/master/catreps-seminar/CategoryOfRepresentations.ipynb)?

**Comment by mohamed-barakat** [comment]
Yes, please. Open a PR (which closes this issue with the commit message).

**Comment by Tschitschibor** [comment]
On the other hand, if I have the same file CategoryOfRepresentations.ipynb both in CatReps and in my bachelor repo, can I coordinate between them with git somehow?

**Comment by mohamed-barakat** [comment]
I wouldn't know how.
